apiVersion: v1
kind: Secret
metadata:
  name: riya-touch-secrets
  namespace: riya-touch
type: Opaque
stringData:
  MONGODB_URI: "mongodb://riya-mongo:27017/riya_touch"
  REDIS_URL: "redis://riya-redis:6379"
  ELASTICSEARCH_URL: "http://riya-elasticsearch:9200"
  JWT_SECRET: "CHANGE_ME_IN_PRODUCTION"
  JWT_EXPIRE: "7d"
  BUSINESS_STATE: "Rajasthan"
  RAZORPAY_KEY_ID: ""
  RAZORPAY_KEY_SECRET: ""
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  NOTIFICATION_PROVIDER: "smart"
  ADMIN_EMAIL: "guptadharmendra280@gmail.com"
  FRONTEND_URL: "https://riyatouch.com"
